{{- $v := .Values }}

apiVersion: v1
data:
  Corefile: |
    {{ $v.cluster.domainSuffix }}:53 {
        errors
        cache 30
        forward . {{ include "call-nested" (list . "k8s-gateway" "k8s-gateway.fullname") }}.{{.Release.Namespace}}.svc.cluster.local
    }
    .:53 {
        errors
        health {
          lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
          ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
          max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system